### ISSUE TITLE
Not able to apply SM17 patch

### ISSUE THREAD

**Issue by Golddouble** [alessivs/supermemo-miscellany#2]
Thank you very much for adding a patch for sm17. 
The line "To apply, run e.g.:" in the "how to do" section was very helpful for me.

Nevertheless:
When I tried to apply the command, there was an error:
```user@mx:~/.local/share/wineprefixes/sm17/dosdevices/c:/SuperMemo
user@mx:~/.local/share/wineprefixes/sm17/dosdevices/c:/SuperMemo
$ xdelta3 -n -d -s sm17.exe compact_navigation_bar.sm1740.delta sm17_patched.exe
xdelta3: not a VCDIFF input: XD3_INVALID_INPUT
xdelta3: normally this indicates that the source file is incorrect
xdelta3: please verify the source file with sha1sum or equivalent
user@mx:~/.local/share/wineprefixes/sm17/dosdevices/c:/SuperMemo
```

**Comment by alessivs** [comment]
Just tried it with no problems with both the `-n` switch present and not present (`-n` skips verification of the original .exe integrity; `-n` is required to apply a second patch and is harmless for applying the first patch). Our sm17.exe checksums are the same.

Anyhow, apparently it's not accepting the .patch file as valid input. 

What is the output of: 

1. `sha1sum compact_navigation_bar.sm1740.delta`
2. `xdelta3 config`
3. `xdelta3 printdelta compact_navigation_bar.sm1740.delta`

Thanks

**Comment by Golddouble** [comment]
```
$ cd ~/.local/share/wineprefixes/sm17/drive_c/SuperMemo/
user@mx:~/.local/share/wineprefixes/sm17/drive_c/SuperMemo
$ sha1sum compact_navigation_bar.sm1740.delta
0bc562476e056fd0d8c32a2ef5c69487d5958c51  compact_navigation_bar.sm1740.delta
user@mx:~/.local/share/wineprefixes/sm17/drive_c/SuperMemo
$ xdelta3 config
Xdelta version 3.0.11, Copyright (C) 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015 Joshua MacDonald
Xdelta comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see "COPYING" for details.
EXTERNAL_COMPRESSION=1
REGRESSION_TEST=1
SECONDARY_DJW=1
SECONDARY_FGK=1
SECONDARY_LZMA=1
UNALIGNED_OK=1
VCDIFF_TOOLS=1
XD3_ALLOCSIZE=16384
XD3_DEBUG=0
XD3_ENCODER=1
XD3_POSIX=1
XD3_STDIO=0
XD3_WIN32=0
XD3_USE_LARGEFILE64=1
XD3_DEFAULT_LEVEL=3
XD3_DEFAULT_IOPT_SIZE=32768
XD3_DEFAULT_SPREVSZ=262144
XD3_DEFAULT_SRCWINSZ=67108864
XD3_DEFAULT_WINSIZE=8388608
XD3_HARDMAXWINSIZE=16777216
sizeof(void*)=8
sizeof(int)=4
sizeof(long)=8
sizeof(long long)=8
sizeof(size_t)=8
sizeof(uint32_t)=4
sizeof(uint64_t)=8
sizeof(usize_t)=4
sizeof(xoff_t)=8
user@mx:~/.local/share/wineprefixes/sm17/drive_c/SuperMemo
$ xdelta3 printdelta compact_navigation_bar.sm1740.delta
xdelta3: not a VCDIFF input: XD3_INVALID_INPUT
xdelta3: normally this indicates that the source file is incorrect
xdelta3: please verify the source file with sha1sum or equivalent
user@mx:~/.local/share/wineprefixes/sm17/drive_c/SuperMemo
```

**Comment by alessivs** [comment]
Everything seems fine except for the checksum of the delta file. Please redownload the delta file, and verify that:

`sha1sum compact_navigation_bar.sm1740.delta`

produces: `4780c0a30f148c8fde750ac0998f5d66565586d3`

If redownloading doesn't yield the same checksum, use git clone, or verify that there is not a proxy or network issue altering your downloaded files.

**Comment by Golddouble** [comment]
Thank you!
Has worked now.

My mistake was that I have downloaded the delta file by directly right clicking the "compact_navigation_bar.sm1740.delta"-link on https://github.com/alessivs/supermemo-miscellany.
Now I have left-clicked the link and then the download button.

But when I have started it, I got this:
![SM17 errors after patch](https://user-images.githubusercontent.com/13977359/79687852-601e2300-824a-11ea-8aba-83f07ccb2d28.gif)

This is one of an item with which I have been experimenting regarding this issue:
https://github.com/alessivs/supermemo-wine/issues/9

When I then close SM17 and start it with the unpatched SM17.exe, then there are no errors at the start.

(I do not need any Items in this SM-Collection. This is only an experimental SM Install)

**Comment by alessivs** [comment]
Those are typical **Internet Explorer** errors. You seem to have started `sm17_Npatched.exe` manually (by double-clicking, or just running `wine <executable`); when doing so, you did so from the default wine prefix (regardless of it being under `.local/share/wineprefixes/`) because it lacks the proper `WINEPREFIX` environment variable. The shortcut, in contrast, is equipped with the correct command line for setting up everything.

1. Back up `~/.local/share/wineprefixes/supermemo17/drive_c/SuperMemo/sm17.exe` (e.g. to `sm17.exe.orig`)
2. Copy `sm17_patched.exe` to `~/.local/share/wineprefixes/supermemo17/drive_c/SuperMemo/sm17.exe`
3. Start SuperMemo 17 from the shortcut (should be in the Education category), or alternatively run this: `WINEPREFIX=~/.local/share/wineprefixes/supermemo17 wine ~/.local/share/wineprefixes/supermemo17/drive_c/SuperMemo/sm17.exe` (the shortcut is much simpler)

**Comment by Golddouble** [comment]
Thank you! Works now.
Yes I was in the wine-explorer of the SM-prefix and have started the "sm17_Npatched.exe" there.
I have now renamed the exe as you suggested and have started SM17 with the same shortcut I used before I did patch "sm17.exe". This works fine.

Nevertheless:
It's still not clear for me, why I can start the unpatched sm17.exe directly in the wine-explorer in the prefix and there is no issue, but can not start sm17.exe when it is patched directly in the wine-explorer in the prefix.

Why doesn't it use also the "default wine prefix", when I start the unpatched SM17.exe by doulble clicking in wine-explorer in the prefix?

Thank you very much. I appreciate your work with SM.  :-)

**Comment by alessivs** [comment]
> Why I can start the unpatched sm17.exe directly in the wine-explorer in the prefix and there is no issue, but can not start sm17.exe when it is patched directly in the wine-explorer in the prefix.

The logical outcome would be that either both fail (using unconfigured/the default wine prefix), or both succeed (using the configured prefix).

One possible explanation is that the wine-explorer was first started from the correct prefix (`~/.local/share/wineprefixes/supermemo17`). The second time it was somehow started from the default prefix (`~/.wine`).

Another possible explanation for the lack of error messages when running sm17 from wine-explorer is that at the time the program was started, the element window had not loaded any HTML components (e.g. the visited element was a folder). These errors are only triggered when loading DLLs needed to display HTML components.
